CREATE DATABASE ng_gamesFinal02_db;

CREATE TABLE game(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(180),
description VARCHAR(255),
image VARCHAR(200),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

RENAME TABLE game to games;

DESCRIBE games;

